const dataRows = [
  {
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'agua sinminerales',
    nomquimatprim:'agua desmineralizada',
    precio_us_dll: 0.07,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 1,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'aqua demin',
    nomquimatprim:'agua desmineralizada',
    precio_us_dll: 0.05,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 1,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'agua sin minerales',
    nomquimatprim:'agua desmineralizada',
    precio_us_dll: 0.08,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 1,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'t245',
    nomquimatprim:'aceite',
    precio_us_dll: 1.05,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 2,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'ace',
    nomquimatprim:'aceite',
    precio_us_dll: 1.01,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 2,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'ace',
    nomquimatprim:'aceite',
    precio_us_dll: 1.08,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 2,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'glicerina',
    nomquimatprim:'glicerina',
    precio_us_dll: 1.18,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 3,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'t342',
    nomquimatprim:'glicerina',
    precio_us_dll: 1.12,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 3,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'glice',
    nomquimatprim:'glicerina',
    precio_us_dll: 1.00,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 3,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'acido estearico',
    nomquimatprim:'acido estearico',
    precio_us_dll: 0.08,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 4,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'alcohol cetilico',
    nomquimatprim:'alcohol cetilico',
    precio_us_dll: 0.80,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 5,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'alco cet',
    nomquimatprim:'alcohol cetilico',
    precio_us_dll: 0.98,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 5,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'dimeticona',
    nomquimatprim:'dimeticona',
    precio_us_dll: 1.28,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 6,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'t654',
    nomquimatprim:'dimeticona',
    precio_us_dll: 1.48,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 6,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'dimeticona',
    nomquimatprim:'dimeticona',
    precio_us_dll: 1.38,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 6,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'t624',
    nomquimatprim:'palmitrato de isopropilo',
    precio_us_dll: 5.48,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 7,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'palmitrato de isopropilo',
    nomquimatprim:'palmitrato de isopropilo',
    precio_us_dll: 8.74,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 7,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'t324',
    nomquimatprim:'propilenglicol',
    precio_us_dll: 3.80,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 8,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'sorbitol',
    nomquimatprim:'sorbitol',
    precio_us_dll: 2.91,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 9,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'t243',
    nomquimatprim:'sorbitol',
    precio_us_dll: 2.48,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 9,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'sorbito',
    nomquimatprim:'sorbitol',
    precio_us_dll: 2.54,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 9,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'carbomero',
    nomquimatprim:'carbomero',
    precio_us_dll: 2.91,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 10,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'t143',
    nomquimatprim:'carbomero',
    precio_us_dll: 3.08,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 10,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'fragancia',
    nomquimatprim:'fragancia',
    precio_us_dll: 24.88,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 11,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'conservador',
    nomquimatprim:'conservador_1',
    precio_us_dll: 5.28,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 12,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'c904',
    nomquimatprim:'conservador_1',
    precio_us_dll: 6.08,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 12,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'conservador_1',
    nomquimatprim:'conservador_1',
    precio_us_dll: 6.43,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 12,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'conservador2',
    nomquimatprim:'conservador_2',
    precio_us_dll: 6.38,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 13,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'c905',
    nomquimatprim:'conservador_2',
    precio_us_dll: 6.08,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 13,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'conservador_2',
    nomquimatprim:'conservador_2',
    precio_us_dll: 5.34,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 13,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'edta',
    nomquimatprim:'edta',
    precio_us_dll: 0.08,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 14,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'v105',
    nomquimatprim:'vitamina liquida',
    precio_us_dll: 10.71,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 15,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'alcohol deionizado',
    nomquimatprim:'alcohol deion',
    precio_us_dll: 3.93,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 16,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'agua deionizada',
    nomquimatprim:'agua deion',
    precio_us_dll: 2.98,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 17,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'e205',
    nomquimatprim:'extractos vegetales',
    precio_us_dll: 4.34,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 18,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'acticeramida',
    nomquimatprim:'acti',
    precio_us_dll: 2.58,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 19,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'pantenol',
    nomquimatprim:'pantenol',
    precio_us_dll: 5.98,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 20,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'p405',
    nomquimatprim:'pantenol',
    precio_us_dll: 9.69,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 20,
  },{
    razonsocialprov: 'grupo_merk',
    nomcomatprim:'aceite de jojoba',
    nomquimatprim:'aceite de jojoba',
    precio_us_dll: 4.08,
    precio_mx_peso: 0.0,
    proveedoresId: 1,
    materiasprimasId: 21,
  },{
    razonsocialprov: 'greffex_sa',
    nomcomatprim:'a705',
    nomquimatprim:'aceite de germen de trigo',
    precio_us_dll: 4.08,
    precio_mx_peso: 0.0,
    proveedoresId: 2,
    materiasprimasId: 22,
  },{
    razonsocialprov: 'asesores_profesionales_sr',
    nomcomatprim:'aceite de germen de trigo',
    nomquimatprim:'aceite de germen de trigo',
    precio_us_dll: 3.58,
    precio_mx_peso: 0.0,
    proveedoresId: 3,
    materiasprimasId: 22,
  },{
    razonsocialprov: 'servicios_empresariales',
    nomcomatprim:'botella cristal 1 lt. tapa',
    nomquimatprim:'na',
    precio_us_dll: 0.20,
    precio_mx_peso: 0.0,
    proveedoresId: 4,
    materiasprimasId: 23,
  },{
    razonsocialprov: 'servicios_empresariales',
    nomcomatprim:'botella cristal 500 ml. tapa',
    nomquimatprim:'na',
    precio_us_dll: 0.18,
    precio_mx_peso: 0.0,
    proveedoresId: 4,
    materiasprimasId: 24,
  },{
    razonsocialprov: 'servicios_empresariales',
    nomcomatprim:'botella cristal 250 ml. tapa',
    nomquimatprim:'na',
    precio_us_dll: 0.08,
    precio_mx_peso: 0.0,
    proveedoresId: 4,
    materiasprimasId: 25,
  },{
    razonsocialprov: 'servicios_empresariales',
    nomcomatprim:'botella cristal 1 lt. spray',
    nomquimatprim:'na',
    precio_us_dll: 0.28,
    precio_mx_peso: 0.0,
    proveedoresId: 4,
    materiasprimasId: 26,
  },{
    razonsocialprov: 'servicios_empresariales',
    nomcomatprim:'botella cristal 500 ml. spray',
    nomquimatprim:'na',
    precio_us_dll: 0.21,
    precio_mx_peso: 0.0,
    proveedoresId: 4,
    materiasprimasId: 27,
  },{
    razonsocialprov: 'servicios_empresariales',
    nomcomatprim:'botella cristal 250 ml. spray',
    nomquimatprim:'na',
    precio_us_dll: 0.12,
    precio_mx_peso: 0.0,
    proveedoresId: 4,
    materiasprimasId: 28,
  },{
    razonsocialprov: 'servicios_empresariales',
    nomcomatprim:'tarro nacarado 300ml Modelo odissey',
    nomquimatprim:'na',
    precio_us_dll: 0.48,
    precio_mx_peso: 0.0,
    proveedoresId: 4,
    materiasprimasId: 29,
  },{
    razonsocialprov: 'servicios_empresariales',
    nomcomatprim:'tarro nacarado 150ml Modelo sunrise',
    nomquimatprim:'na',
    precio_us_dll: 0.28,
    precio_mx_peso: 0.0,
    proveedoresId: 4,
    materiasprimasId: 30,
  },{
    razonsocialprov: 'productos_practicos_sa',
    nomcomatprim:'empaque carton p/tarro odissey',
    nomquimatprim:'na',
    precio_us_dll: 0.02,
    precio_mx_peso: 0.0,
    proveedoresId: 5,
    materiasprimasId: 31,
  },{
    razonsocialprov: 'productos_practicos_sa',
    nomcomatprim:'empaque carton p/tarro sunrise',
    nomquimatprim:'na',
    precio_us_dll: 0.01,
    precio_mx_peso: 0.0,
    proveedoresId: 5,
    materiasprimasId: 32,
  }
];

exports.seed = function(knex, Promise) {
  return knex('matprimxprov')
    .del()
    .then(() => {
      return knex('matprimxprov')
        .insert(dataRows);
    });
}
